fixed orientdb
monk-io/monk-orientdb pull request #1
Opened 2023-04-09 00:34 UTC by Burakhan

2023-04-09 08:11 UTC, CuteAnonymousPanda requested changes
Since you're removing a var from template you need to update README.md as well: https://github.com/monk-io/monk-orientdb/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L58

Also the title of the PR is wrong Should be more like update metadata, reorganise etc.. 

Additionally, host-port is not working yet and doesn't expose port as `ports:`.

Also, you can just do "base" with bare minimum with metadata, image. Then update "db" runnable, which inherits base and adds ports/services.

2023-04-09 19:30 UTC, Burakhan commented
@CuteAnonymousPanda Thank you for review. Fixed it

2023-04-10 09:59 UTC, CuteAnonymousPanda commented
Sweet, looks good to me now. Can you please just squash commits on PR?

2023-04-10 09:59 UTC, CuteAnonymousPanda approved these changes

2023-04-28 21:58 UTC, merged